<button id ="btn">
    클릭
</button>


<script>
    var btn = document.querySelector('#btn');

    btn.addEventListener('click', async() => {
        var click = new Promise((resolve, reject) => {
            resolve('성공');
        });

        try {
            var result = await click;
            console.log('result', result);
        } catch {
            console.log('실패했습니다.')
        };

    })


    const test = async() => {
        const btn = document.querySelector('#btn');;

        const pro = new Promise((resolve, reject) => {
            btn.addEventListener('click', () => {
                resolve('클릭하셨습니다.');
            })
        })

        try {
            const result = await pro;
            console.log('result', result);
        } catch {
            console.log('fail');
        };
    };

    test();

    /*
        잘못된 방법
        <script>
            async function 프로미스(){
                document.getElementById('test').addEventListener('click', function(){
                return '성공했어요'
                });
            }

            async function 버튼누르기(){
                var 결과 = await 프로미스();
                console.log(결과)
            }

            버튼누르기();
        <script>
        프로미스에 resolve를 통해 return 하는 것이 아닌 바로 return을 하면
        return은 undefined다.

        async가 Promise를 퉤 뱉는다고해서 async function 프로미스() 를 쓰고 이벤트리스너를 안에 담긴 했는데

        버튼 누르면 return 어쩌구에 의해서 성공판정이 될거라고 기대했지만 안됩니다.

        실은 return '성공했어요' 이게 async function의 return이 아니고 이벤트리스너안의 함수의 return문이라 문제되는 것도 있지만 

        그것보다 더 중요한 문제는 이겁니다.

        

        1. 이벤트 리스너안의 코드는 바로 실행되지 않습니다. 버튼 누를 때 실행됩니다.

        2. 그래서 컴퓨터가 코드를 쭉 읽을 때 async function 프로미스() 함수 내부는 빈칸과 동일합니다.

        3. 자바스크립트는 function 안이 빈칸이면 그냥 자동으로 return undefined 를 채워 실행합니다.  

        (그럼 3번에 의해서 async function 프로미스()는 0초만에 자동으로 성공()판정이 됩니다)

        

        

        그래서 하단의

        var 결과 = await 프로미스();

        이 코드는 프로미스()가 0초만에 성공판정이 내려진 상태로 실행되며 (그 함수에 return undefined가 자동으로 채워지니까요)

        var 결과 = undefined 와 동일한 뜻입니다.

        그래서 코드가 이상해진 것입니다. 

        

        

        하지만 Promise로 만들어서 직접 성공(), 실패() 경우를 지정해준다면

        await이 잘 기다려줍니다. 

    */




    /*
        async 키워드를 쓰면 Promise 오브젝트가 자동으로 생성된다.
        new Promise()를 선언할 필요가 없다.
        이 키워드는 함수 앞에서만 사용 가능하다.

        그럼 함수 자체가 Promise가 된다.
        함수를 실행할 때 뒤에 then을 붙일 수 있다. Promise()니까

        async function 더하기() {
            1+1
        };

        더하기().then(function() {
            console.log('더하기 성공');
        });

        함수 안에서 연산한 결과를 then 안에서 사용하고 싶다면
        async function 더하기 () {
            return 1 + 1; 
        };

        더하기().then(function(결과) {
            console.lgo(결과);
        });

        return 오른쪽에 결과를 적어주면 된다. 그럼 then함수까지 해당 값을 전달이 가능하다.




        then()함수가 귀찮다면 await 키워드를 쓸 수 있다.

        async 키워드를 쓴 함수 안에서는 await을 사용할 수 있다.
        await은 그냥 프로미스.then()의 대체품이다.
        하지만 then보다 훨씬 문법이 간단하다.

        async function 더하기() {
            var 어려운 연산 = new Promise((성공, 실패) => {
                var 결과 = 1 + 1;
                성공();
            })

            어려운연산.then();
        }
        더하기();
        혹은 Promise 만들기 귀찮다면 어려운 연산을 함수로 만든 후 async를 쓰면 된다.

        그럼 이제 어려운연산.then() 이렇게 성공시 특정 코드를 실행할 수 있다.
        근데 .then()이게 너무 복잡해서 보기 싫다면
        await라는 키워드를 사용 가능하다.

        async function 더하기() {
            var 어려운 연산 = new Promise((성공, 실패) => {
                var 결과 = 1 + 1;
                성공();
            });

            var 결과 = await 어려운연산;

        }

        더하기();

        어려운연산.then()과 매우 유사한 문법이다.
        정확한 뜻은 어려운연산 Promise를 기다린 다음에 완료되면 결과를 변수에 담아주세요.

        연산 결과를 출력하고 싶다면 성공 함수에 파라미터를 담아주면 된다.

        async fucntion 더하기(){
            var 어려운연산 = new Promsie((성공, 실패) => {
                var 결과 = 1+1;
                성공(결과);
            });
            var 결과 = await 어려운 연산;
            console.log(결과);
        };
        더하기();

        성공()함수 안에 있는 2라는 파라미터는
        var 결과라는 변수에 저장
        그럼 Promise의 연산 결과를 출력할 수 있다
        (주의) 비동기식처리되는 코드를 담는다면 await 기다리는 동안 브라우저가 잠깐 멈출 수 있다.


        await은 실패하면 에러가 나고 코드가 멈춥니다

 

        Promise가 실패하는 하단 코드를 실행해봅시다.

        async function 더하기(){
        var 어려운연산 = new Promise((성공, 실패)=>{
            실패();
        });
        var 결과 = await 어려운연산;
        console.log(결과);
        }
        더하기();
        어려운연산이라는 Promise가 실패할 경우

        await 어려운연산이라는 코드는 에러가 나고 코드실행을 멈춥니다.

        그럼 await 하단에 있는 코드들은 더 이상 실행이 되지 않겠죠.

        

        

        그래서 Promise가 실패할 경우

        코드실행을 멈추고 싶지 않으면 약간 특별한 방법이 필요합니다. 

        async function 더하기(){
        var 어려운연산 = new Promise((성공, 실패)=>{
            실패();
        });
        try {  var 결과 = await 어려운연산 }
        catch { 어려운연산 Promise가 실패할 경우 실행할 코드 }
        }
        try catch라는 자바스크립트 문법인데,

        try {} 안의 코드가 에러가 나고 멈출 경우

        대신 catch {} 내부의 코드를 실행해줍니다. 

        

        이렇게 에러처리를 하실 수 있습니다. 더 복잡하니까 그냥 then() 이런거 쓰셈 

        어려운연산이라는 Promise가 실패()가 안날거라고 자신하면 try/catch를 굳이 쓸 필요는 없으니 코드가 더 간단해질 수도 있습니다. 
    */


</script>